cam_intrinsic:
  matrix:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 747.9932
  - 0.0
  - 655.5036
  - 0.0
  - 746.6126
  - 390.1168
  - 0.0
  - 0.0
  - 1.0
cam_to_WCS_extrinsic:
  matrix:
  - -0.349066
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - -10.9
  - 0
radar_to_cam_extrinsic:
  matrix:
  - 1
  - 2
  - 3
  - 4
  - 1.58
  - 0.0
  - 0.050000000000000044
  - 0.7000000000000002
  - 0.0
  - 0.0
road_mask:
  array:
    x:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    y:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    x: []
    y: []
  num: 0